"""add clients table and user cargo client_id

Revision ID: 3bfe205e7a1e
Revises: b1c2d3e4f5a6
Create Date: 2026-07-13 00:54:22.801549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bfe205e7a1e'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('cargo', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('client_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_client_id'), 'users', ['client_id'], unique=False)
    op.create_foreign_key(
        'fk_users_client_id_clients', 'users', 'clients', ['client_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_client_id_clients', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_client_id'), table_name='users')
    op.drop_column('users', 'client_id')
    op.drop_column('users', 'cargo')
    op.drop_table('clients')
    # ### end Alembic commands ###
