"""add fact_audiencia fecha index

Revision ID: 470711ded83e
Revises: a4a57f5ccd0c
Create Date: 2026-07-04 23:09:19.236051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '470711ded83e'
down_revision: Union[str, None] = 'a4a57f5ccd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fact_audiencia_fecha', 'fact_audiencia', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_audiencia_fecha', table_name='fact_audiencia')
    # ### end Alembic commands ###
