"""initial schema

Revision ID: e194c4ef21ac
Revises: 
Create Date: 2026-07-04 21:18:15.753629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e194c4ef21ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_programa',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('canal', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.Enum('podcast', 'programa', name='program_type'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'interno', 'cliente', name='user_role'), server_default='cliente', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('dim_auspicios',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('mes_num', sa.SmallInteger(), nullable=False),
    sa.Column('mes_nombre', sa.String(length=20), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('auspiciador', sa.String(length=200), nullable=False),
    sa.CheckConstraint('mes_num BETWEEN 1 AND 12', name='ck_dim_auspicios_mes_num_range'),
    sa.ForeignKeyConstraint(['programa_id'], ['dim_programa.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mes_num', 'programa_id', 'auspiciador', name='uq_dim_auspicios_upsert_key')
    )
    op.create_index('ix_dim_auspicios_programa', 'dim_auspicios', ['programa_id'], unique=False)
    op.create_table('fact_keywords',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('mes_num', sa.SmallInteger(), nullable=False),
    sa.Column('mes_nombre', sa.String(length=20), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(length=200), nullable=False),
    sa.Column('occurrences', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sentimiento', sa.Enum('positivo', 'negativo', 'neutral', name='sentiment_type'), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('mes_num BETWEEN 1 AND 12', name='ck_fact_keywords_mes_num_range'),
    sa.ForeignKeyConstraint(['programa_id'], ['dim_programa.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes_num', 'programa_id', 'hashtag', 'sentimiento', name='uq_fact_keywords_upsert_key')
    )
    op.create_index('ix_fact_keywords_programa_periodo', 'fact_keywords', ['programa_id', 'anio', 'mes_num'], unique=False)
    op.create_index('ix_fact_keywords_sentimiento', 'fact_keywords', ['sentimiento'], unique=False)
    op.create_table('fact_sentimiento',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('mes_num', sa.SmallInteger(), nullable=False),
    sa.Column('mes_nombre', sa.String(length=20), nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('score_positivo', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('score_negativo', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('score_neutral', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('abs(score_positivo + score_negativo + score_neutral - 1) <= 0.01', name='ck_fact_sentimiento_scores_sum_to_one'),
    sa.CheckConstraint('mes_num BETWEEN 1 AND 12', name='ck_fact_sentimiento_mes_num_range'),
    sa.CheckConstraint('score_negativo BETWEEN 0 AND 1', name='ck_fact_sentimiento_negativo_range'),
    sa.CheckConstraint('score_neutral BETWEEN 0 AND 1', name='ck_fact_sentimiento_neutral_range'),
    sa.CheckConstraint('score_positivo BETWEEN 0 AND 1', name='ck_fact_sentimiento_positivo_range'),
    sa.ForeignKeyConstraint(['programa_id'], ['dim_programa.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio', 'mes_num', 'programa_id', name='uq_fact_sentimiento_upsert_key')
    )
    op.create_index('ix_fact_sentimiento_programa_periodo', 'fact_sentimiento', ['programa_id', 'anio', 'mes_num'], unique=False)
    op.create_table('upload_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('DATA', 'KEYWORDS', 'SPLIT_SENSE', 'AUSPICIOS', name='upload_file_type'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'success', 'error', name='upload_status'), server_default='pending', nullable=False),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_upload_logs_uploaded_by', 'upload_logs', ['uploaded_by_id'], unique=False)
    op.create_table('fact_audiencia',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('mes_num', sa.SmallInteger(), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('semana_num', sa.SmallInteger(), nullable=False),
    sa.Column('puesto', sa.SmallInteger(), nullable=True),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('es_emision', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('vistas_diarias', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('busquedas_diarias', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comentarios', sa.BigInteger(), nullable=True),
    sa.Column('engagement', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pico_max_vivo', sa.BigInteger(), nullable=True),
    sa.Column('promedio_vivo', sa.BigInteger(), nullable=True),
    sa.Column('formato', sa.String(length=50), nullable=True),
    sa.Column('titulo_video', sa.Text(), nullable=True),
    sa.Column('link_video', sa.Text(), nullable=True),
    sa.Column('upload_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('mes_num BETWEEN 1 AND 12', name='ck_fact_audiencia_mes_num_range'),
    sa.ForeignKeyConstraint(['programa_id'], ['dim_programa.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'programa_id', name='uq_fact_audiencia_fecha_programa')
    )
    op.create_index('ix_fact_audiencia_anio_mes', 'fact_audiencia', ['anio', 'mes_num'], unique=False)
    op.create_index('ix_fact_audiencia_anio_semana', 'fact_audiencia', ['anio', 'semana_num'], unique=False)
    op.create_index('ix_fact_audiencia_programa', 'fact_audiencia', ['programa_id'], unique=False)
    # ### end Alembic commands ###

    # Trigger de base de datos para users.updated_at (TDD §7.2: "Auto-update trigger").
    # No se usa el onupdate de SQLAlchemy porque solo se dispara vía ORM, no ante un
    # UPDATE SQL directo (p. ej. desde el editor de Supabase o un script de datos).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_users_set_updated_at
        BEFORE UPDATE ON users
        FOR EACH ROW
        EXECUTE FUNCTION set_updated_at();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_audiencia_programa', table_name='fact_audiencia')
    op.drop_index('ix_fact_audiencia_anio_semana', table_name='fact_audiencia')
    op.drop_index('ix_fact_audiencia_anio_mes', table_name='fact_audiencia')
    op.drop_table('fact_audiencia')
    op.drop_index('ix_upload_logs_uploaded_by', table_name='upload_logs')
    op.drop_table('upload_logs')
    op.drop_index('ix_fact_sentimiento_programa_periodo', table_name='fact_sentimiento')
    op.drop_table('fact_sentimiento')
    op.drop_index('ix_fact_keywords_sentimiento', table_name='fact_keywords')
    op.drop_index('ix_fact_keywords_programa_periodo', table_name='fact_keywords')
    op.drop_table('fact_keywords')
    op.drop_index('ix_dim_auspicios_programa', table_name='dim_auspicios')
    op.drop_table('dim_auspicios')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('dim_programa')
    # ### end Alembic commands ###
